FROM python:3.12-slim-bookworm AS flask-builder

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y git && \
    pip install --no-cache-dir -r requirements.txt

COPY pre-cache-models.py .
RUN python pre-cache-models.py > pre-cache-log.txt   
