---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hf-zephyr-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hf-zephyr
  template:
    metadata:
      labels:
        app: hf-zephyr
    spec:
      containers:
      - name: hf-zephyr
        image: antonbiz/hf-zephyr:1.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: hf-zephyr-service
spec:
  type: LoadBalancer
  selector:
    app: hf-zephyr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hf-zephyr-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hf-zephyr-service
            port: 
              number: 80
---